### ISSUE TITLE
Adjust logging level for `tracing` crate

### ISSUE THREAD

**Issue by CodingAnarchy** [djc/gcp_auth#100]
A number of the functions in this library are instrumented with `tracing::instrument`, but that defaults to an `INFO` logging level. It would be helpful to set these to something higher like `DEBUG` so we can manage whether these low level methods will show up in the logs when we instrument our own applications.

**Comment by djc** [comment]
Sure, would you be able to submit a PR with specific suggestions?

**Comment by CodingAnarchy** [comment]
@djc Sure thing, I have opened #101 to adjust these log levels. Thanks!
